export const GET_MEMORIES = 'GET_MEMORIES'
export const GET_MEMORIES_SUCCESS = 'GET_MEMORIES_SUCCESS'
export const GET_MEMORIES_FAILED = 'GET_MEMORIES_FAILED'

export const CREATE_MEMORY = 'CREATE_MEMORY'
export const CREATE_MEMORY_SUCCESS = 'CREATE_MEMORY_SUCCESS'
export const CREATE_MEMORY_FAILED = 'CREATE_MEMORY_FAILED'

export const CREATE_USER = 'CREATE_USER'
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS'
export const CREATE_USER_FAILED = 'CREATE_USER_FAILED'

export const USER_LOGIN = 'USER_LOGIN'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED'

export const LOGOUT = 'LOGOUT'

export const UPDATE_ID = 'UPDATE_ID'

export const UPDATE_MEMORY = 'UPDATE_MEMORY'
export const UPDATE_MEMORIES_SUCCESS = 'UPDATE_MEMORIES_SUCCESS'
export const UPDATE_MEMORIES_FAILED = 'UPDATE_MEMORIES_FAILED'

export const DELETE_MEMORY = 'DELETE_MEMORY'
export const DELETE_MEMORY_SUCCESS = 'DELETE_MEMORY_SUCCESS'
export const DELETE_MEMORY_FAILED = 'DELETE_MEMORY_FAILED'

export const MAKENULLID = 'MAKENULLID'