export const GET_MEMORIES = 'GET_MEMORIES'
export const GET_MEMORIES_SUCCESS = 'GET_MEMORIES_SUCCESS'
export const GET_MEMORIES_FAILED = 'GET_MEMORIES_FAILED'

export const CREATE_MEMORY = 'CREATE_MEMORY'
export const CREATE_MEMORY_SUCCESS = 'CREATE_MEMORY_SUCCESS'
export const CREATE_MEMORY_FAILED = 'CREATE_MEMORY_FAILED'